import json

path = r"c:\Users\Emabe\Documents\GitHub\xlstm\rust\colab\bitnet_grouped_350m.ipynb"

with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

phase5_lines = [
    "# ==============================================================================\n",
    "# PHASE 5: WEIGHT EXPORT, BIT-PACKING & VERIFICATION\n",
    "# ==============================================================================\n",
    "\n",
    "def pack_ternary_weights(w_quant):\n",
    "    \"\"\"Pack ternary weights {-1,0,1} into 2-bit, 4 per uint8 byte.\"\"\"\n",
    "    w_unsigned = torch.where(w_quant == -1, torch.tensor(2, dtype=torch.int8, device=w_quant.device), w_quant.to(torch.int8))\n",
    "    flat = w_unsigned.view(-1)\n",
    "    pad_len = (4 - (len(flat) % 4)) % 4\n",
    "    if pad_len > 0:\n",
    "        flat = F.pad(flat, (0, pad_len), value=0)\n",
    "    flat_reshaped = flat.view(-1, 4)\n",
    "    packed = (flat_reshaped[:, 0] | (flat_reshaped[:, 1] << 2) | (flat_reshaped[:, 2] << 4) | (flat_reshaped[:, 3] << 6))\n",
    "    return packed.to(torch.uint8)\n",
    "\n",
    "def unpack_ternary_weights(packed, original_shape):\n",
    "    \"\"\"Unpack uint8 byte array back into ternary {-1,0,1} tensor.\"\"\"\n",
    "    val0 = packed & 3\n",
    "    val1 = (packed >> 2) & 3\n",
    "    val2 = (packed >> 4) & 3\n",
    "    val3 = (packed >> 6) & 3\n",
    "    flat = torch.stack([val0, val1, val2, val3], dim=1).view(-1)\n",
    "    flat_signed = torch.where(flat == 2, torch.tensor(-1, dtype=torch.int8, device=packed.device), flat.to(torch.int8))\n",
    "    num_elements = original_shape[0] * original_shape[1]\n",
    "    return flat_signed[:num_elements].view(original_shape)\n",
    "\n",
    "def export_ternary_weights(model, pack=True):\n",
    "    \"\"\"Extract ternary weights + scales for BitLinear, FP16 for others.\"\"\"\n",
    "    exported_dict = {}\n",
    "    for name, module in model.named_modules():\n",
    "        if isinstance(module, BitLinear):\n",
    "            _, w_quant, beta = quantize_weight_grouped(module.weight.data.float(), module.group_size)\n",
    "            if pack:\n",
    "                packed_w = pack_ternary_weights(w_quant)\n",
    "                exported_dict[f\"{name}.weight_ternary_packed\"] = packed_w.cpu()\n",
    "                exported_dict[f\"{name}.original_shape\"] = torch.tensor(w_quant.shape)\n",
    "            else:\n",
    "                exported_dict[f\"{name}.weight_ternary\"] = w_quant.to(torch.int8).cpu()\n",
    "            exported_dict[f\"{name}.scale_factors\"] = beta.to(torch.float16).cpu()\n",
    "            if module.bias is not None:\n",
    "                exported_dict[f\"{name}.bias\"] = module.bias.data.to(torch.float16).cpu()\n",
    "        else:\n",
    "            for param_name, param in module.named_parameters(recurse=False):\n",
    "                full_name = f\"{name}.{param_name}\" if name else param_name\n",
    "                if not any(full_name.startswith(bl_name) for bl_name, m in model.named_modules() if isinstance(m, BitLinear)):\n",
    "                    exported_dict[full_name] = param.data.to(torch.float16).cpu()\n",
    "    return exported_dict\n",
    "\n",
    "\n",
    "# --- 1. Export in FP16 (on a COPY, don't modify model in-place) ---\n",
    "print('\\U0001f4be Saving standard FP16 state dict...')\n",
    "fp16_path = 'bitnet_model_fp16.pt'\n",
    "fp16_state = {k: v.half().cpu() for k, v in model.state_dict().items()}\n",
    "torch.save(fp16_state, fp16_path)\n",
    "\n",
    "# --- 2. Export in Packed Compressed Ternary format ---\n",
    "print('\\U0001f4be Saving packed Ternary weights...')\n",
    "ternary_dict = export_ternary_weights(model, pack=True)\n",
    "ternary_path = 'bitnet_model_ternary.pt'\n",
    "torch.save(ternary_dict, ternary_path)\n",
    "\n",
    "# Calculate and compare file sizes\n",
    "fp16_size = os.path.getsize(fp16_path) / 1024**2\n",
    "ternary_size = os.path.getsize(ternary_path) / 1024**2\n",
    "print(f'\\U0001f4ca FP16 Export Size: {fp16_size:.2f} MB')\n",
    "print(f'\\U0001f4ca Packed Ternary Export Size: {ternary_size:.2f} MB')\n",
    "print(f'\\U0001f4c9 Size reduction: {((1 - ternary_size / fp16_size) * 100):.2f}%!')\n",
    "\n",
    "\n",
    "# Verification Test for Phase 5\n",
    "# Tests the pack/unpack roundtrip directly on ternary weights.\n",
    "# We do NOT compare model outputs because BitLinear.forward() re-quantizes\n",
    "# loaded weights (double-quantization), which changes the scale factor.\n",
    "print('\\n=== TEST PHASE 5 ===')\n",
    "try:\n",
    "    loaded_dict = torch.load(ternary_path, weights_only=False)\n",
    "    total_weights = 0\n",
    "    total_errors = 0\n",
    "    max_scale_err = 0.0\n",
    "    \n",
    "    for name, module in model.named_modules():\n",
    "        if isinstance(module, BitLinear):\n",
    "            # Get original ternary weights from the live model\n",
    "            _, w_quant_orig, beta_orig = quantize_weight_grouped(module.weight.data.float(), module.group_size)\n",
    "            \n",
    "            # Unpack saved weights\n",
    "            packed_key = f'{name}.weight_ternary_packed'\n",
    "            if packed_key in loaded_dict:\n",
    "                packed_w = loaded_dict[packed_key].to(device)\n",
    "                shape = tuple(loaded_dict[f'{name}.original_shape'].tolist())\n",
    "                w_quant_loaded = unpack_ternary_weights(packed_w, shape).to(device)\n",
    "                \n",
    "                # Compare ternary values (must be EXACT match)\n",
    "                mismatches = (w_quant_orig.to(torch.int8) != w_quant_loaded).sum().item()\n",
    "                total_errors += mismatches\n",
    "                total_weights += w_quant_orig.numel()\n",
    "                \n",
    "                # Compare scale factors\n",
    "                beta_loaded = loaded_dict[f'{name}.scale_factors'].to(device)\n",
    "                scale_err = (beta_orig.half() - beta_loaded).abs().max().item()\n",
    "                max_scale_err = max(max_scale_err, scale_err)\n",
    "    \n",
    "    print(f'Total ternary weights verified: {total_weights:,}')\n",
    "    print(f'Pack/Unpack mismatches: {total_errors}')\n",
    "    print(f'Max scale factor error (FP16 roundtrip): {max_scale_err:.2e}')\n",
    "    assert total_errors == 0, f'Found {total_errors} mismatches in pack/unpack!'\n",
    "    assert max_scale_err < 1e-3, f'Scale factor error too high: {max_scale_err}'\n",
    "    print('\\u2705 Test Passed: Bit-packing roundtrip is lossless! All ternary weights and scales match perfectly.')\n",
    "except Exception as e:\n",
    "    print(f'\\u274c Test Failed: {str(e)}')\n",
]

# Find and replace Phase 5 code cell
for cell in nb["cells"]:
    if cell["cell_type"] == "code":
        src = "".join(cell.get("source", []))
        if "PHASE 5:" in src and "pack_ternary" in src:
            cell["source"] = phase5_lines
            print("Phase 5 cell patched!")
            break

with open(path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Notebook saved.")
