# -*- coding: utf-8 -*-
"""mnist_w_tpu_xla.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDyzLVlhnFpY5m3U-ENB4isJs93J5p3s

# Fashion MNIST with TPU & XLA

## Install Packages
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install torch torchvision torch_xla[tpu] libtpu tpu-info

!tpu-info

"""## Imports & Define Model"""

import time

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

# PyTorch/XLA specific imports
import torch_xla
import torch_xla.core.xla_model as xm

# Define the CNN Model
class MNISTNet(nn.Module):
    def __init__(self):
        super(MNISTNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.fc1 = nn.Linear(7*7*64, 128) # Adjusted for 28x28 image, 2 pooling layers
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2(x), 2))
        x = x.view(-1, 7*7*64) # Flatten the tensor
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

"""### Define Training & Test functions"""

import os
os.environ["XLA_USE_BF16"] = "1"


def train_mnist():
    # Training parameters
    epochs = 50
    learning_rate = 0.01
    momentum = 0.5
    batch_size = 512

    # 1. Acquire the XLA device
    device = torch_xla.device()
    print(f"Running on XLA device: {device}")

    # Load MNIST dataset
    train_loader = torch.utils.data.DataLoader(
        datasets.MNIST('./data', train=True, download=True,
                        transform=transforms.Compose([
                            transforms.ToTensor()
                            #transforms.Normalize((0.1307,), (0.3081,))
                       ])),
        batch_size=batch_size, shuffle=True)

    test_loader = torch.utils.data.DataLoader(
        datasets.MNIST('./data', train=False,
                        transform=transforms.Compose([
                            transforms.ToTensor()
                            #transforms.Normalize((0.1307,), (0.3081,))
                        ])),
        batch_size=1000, shuffle=False)

    # 2. Initialize the model and move it to the XLA device
    model = MNISTNet().to(device)

    # Define loss function and optimizer
    loss_fn = nn.NLLLoss()
    optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=momentum)

    print("Starting training...")
    start = time.time()
    for epoch in range(1, epochs + 1):
        model.train()
        for batch_idx, (data, target) in enumerate(train_loader):
            optimizer.zero_grad()

            # 3. Move data and target to the XLA device
            data, target = data.to(device), target.to(device)

            output = model(data)
            loss = loss_fn(output, target)
            loss.backward()

            optimizer.step()

            # 4. Synchronize: Tell XLA to execute the accumulated operations
            # For single device training, torch_xla.sync() is often used.
            # For multi-device training (covered later), xm.optimizer_step(optimizer)
            # also performs this synchronization.
            torch_xla.sync()

            if batch_idx % 100 == 0:
                print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} '
                      f'({100. * batch_idx / len(train_loader):.0f}%)]\tLoss: {loss.item():.6f}')

    print("Training finished!")
    end = time.time()

    runtime = end - start
    print(f"Runtime: {runtime:.4f} seconds")
    test(model, device, test_loader)

def test(model, device, test_loader):
    model.eval()  # Set model to evaluation mode
    correct = 0
    with torch.no_grad(): # No gradients needed for accuracy
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            # Get the index of the max log-probability (the prediction)
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

    accuracy = 100. * correct / len(test_loader.dataset)
    print(f'Test Accuracy: {accuracy:.2f}%\n')
    return accuracy

!lscpu
!cat /proc/cpuinfo

if __name__ == '__main__':
    train_mnist()